export type RpcGatewayEnv = {
  SAFECAFE_RPC_ALLOW_ALL_WALLETS?: string
  SAFECAFE_AUTH_SECRET?: string
  SAFECAFE_MOCK_ACCOUNT?: string
  SAFECAFE_MOCK_ACCOUNT_LIVE?: string
  SAFECAFE_RPC_URL?: string
  SAFECAFE_RPC_URLS?: string
}
