export type RpcGatewayEnv = {
  SAFECAFE_RPC_ALLOW_ALL_WALLETS?: string
  SAFECAFE_AUTH_SECRET?: string
  SAFECAFE_MOCK_ACCOUNT?: string
  SAFECAFE_MOCK_ACCOUNT_LIVE?: string
  SAFECAFE_AGENT_AUTH?: string
  SAFECAFE_RPC_URL?: string
  SAFECAFE_RPC_URLS?: string
  SAFECAFE_LLM_API_BASE?: string
  SAFECAFE_LLM_API_MODEL?: string
  SAFECAFE_LLM_API_KEY?: string
  SAFECAFE_LLM_TIMEOUT_MS?: string
  SAFECAFE_LLM_MAX_TOKENS?: string
  VITE_AGENT_AUTH?: string
}
