import { privateKeyToAccount } from "viem/accounts"
import type { Address } from "viem"
import {
  DEFAULT_RPC_URLS,
  fetchRewardProof,
  fetchValidators,
  findValidator,
  formatSafe,
  mockValidators,
  parseSafeAmount,
  readAccountSnapshot,
  readHealth,
  readValidatorPositions,
  type TxPlan,
} from "../src/protocol"
import {
  createProductPublicClient,
  output,
  printPlan,
  readPrivateKey,
  resolveRpcUrl,
  sendPlanTransactions,
  writeSafePayloadFile,
  type CliGlobalOptions,
} from "../src/shared/cli"
import { parseAddress } from "../src/shared/utils"

export type GlobalOptions = CliGlobalOptions

export type WriteOptions = {
  account?: string
  dryRun?: boolean
  send?: boolean
  yes?: boolean
  privateKeyEnv?: string
  safePayload?: string
}

export const rpcEnvNames = ["SAFECAFE_RPC_URL", "SAFENET_RPC_URL"] as const
const safePayloadDescription = "Generated by Safecafe CLI. Review every transaction before signing."

export function createClient(globals: GlobalOptions) {
  return createProductPublicClient(globals, process.env, rpcEnvNames)
}

export function resolvePlanningAccount(options: WriteOptions, globals: GlobalOptions): Address | undefined {
  if (globals.mock) return undefined
  if (options.account) return parseAddress(options.account, "account")
  if (options.send) return privateKeyToAccount(readPrivateKey(options.privateKeyEnv, process.env)).address
  throw new Error("--account is required for live planning. Use --send with --private-key-env for EOA sending.")
}

export async function resolveValidator(query: string, mock?: boolean): Promise<Address> {
  const direct = tryParseAddress(query)
  if (direct) return direct
  const validators = mock ? mockValidators : await fetchValidators()
  const validator = findValidator(validators, query)
  if (!validator) throw new Error(`Unknown validator: ${query}`)
  return validator.address
}

function tryParseAddress(value: string): Address | null {
  try {
    return parseAddress(value)
  } catch {
    return null
  }
}

export async function assertStakePossible(globals: GlobalOptions, account: Address, validator: Address, amountText: string) {
  const amount = parseSafeAmount(amountText)
  const client = createClient(globals)
  const [snapshot, validators] = await Promise.all([
    readAccountSnapshot(client, account),
    fetchValidators(),
  ])
  const validatorMetadata = findValidator(validators, validator)
  if (validatorMetadata?.status === "inactive") throw new Error(`Validator is inactive: ${validatorMetadata.label}`)
  if (snapshot.safeBalance < amount) {
    throw new Error(`Insufficient SAFE balance. Need ${formatSafe(amount, 6)}, have ${formatSafe(snapshot.safeBalance, 6)}.`)
  }
}

export async function assertUnstakePossible(globals: GlobalOptions, account: Address, validator: Address, amountText: string) {
  const amount = parseSafeAmount(amountText)
  const [position] = await readValidatorPositions(createClient(globals), account, [
    {
      address: validator,
      label: "Selected validator",
      status: "active",
      commission: 0,
      participationRate: 0,
      totalStake: 0n,
      userStake: 0n,
    },
  ])
  if (position.userStake < amount) {
    throw new Error(`Insufficient validator stake. Need ${formatSafe(amount, 6)}, have ${formatSafe(position.userStake, 6)}.`)
  }
}

export async function assertWithdrawalClaimable(globals: GlobalOptions, account: Address) {
  const snapshot = await readAccountSnapshot(createClient(globals), account)
  const [amount, claimableAt] = snapshot.nextClaimableWithdrawal
  const now = BigInt(Math.floor(Date.now() / 1000))
  if (amount <= 0n || claimableAt > now) {
    const suffix = claimableAt > 0n ? ` Next claimable at ${new Date(Number(claimableAt) * 1000).toISOString()}.` : ""
    throw new Error(`No withdrawal is claimable yet.${suffix}`)
  }
}

export async function assertRewardsClaimable(globals: GlobalOptions, account: Address) {
  const client = createClient(globals)
  const [proof, snapshot, health] = await Promise.all([
    fetchRewardProof(account),
    readAccountSnapshot(client, account),
    readHealth(client),
  ])
  if (!proof || !proof.proof) throw new Error("No reward proof found for account.")
  if (proof.merkleRoot.toLowerCase() !== health.merkleRoot.toLowerCase()) throw new Error("Reward proof Merkle root does not match the live contract root.")
  const cumulativeAmount = BigInt(proof.cumulativeAmount)
  if (cumulativeAmount <= snapshot.cumulativeClaimed) throw new Error("Rewards are already fully claimed.")
}

export async function handlePlan(globals: GlobalOptions, plan: TxPlan, options: WriteOptions) {
  if (globals.mock && options.send) throw new Error("--mock cannot be combined with --send")

  if (options.safePayload) {
    const payload = writeSafePayloadFile(plan, options.safePayload, safePayloadDescription)
    if (globals.json) {
      output(globals, payload, () => undefined)
      return
    }
    printPlan(plan)
    console.log("")
    console.log(`Safe Transaction Builder payload written to ${options.safePayload}`)
    return
  }

  output(globals, plan, () => printPlan(plan))

  if (!options.send) return
  if (!options.yes) throw new Error("--yes is required with --send to confirm live transaction submission")

  await sendPlanTransactions(plan, {
    privateKey: readPrivateKey(options.privateKeyEnv, process.env),
    rpcUrl: resolveRpcUrl(globals, process.env, rpcEnvNames) || DEFAULT_RPC_URLS[0],
    onSubmitted: (label, hash) => console.log(`Submitted ${label}: ${hash}`),
    onConfirmed: (label, blockNumber) => console.log(`Confirmed ${label}: block ${blockNumber}`),
  })
}
